import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import worker from '../worker.js';
function memoryDB(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');const prepare=(query,args=[])=>({bind(...p){return prepare(query,p)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}}}});return {sql,prepare,async batch(statements){sql.exec('BEGIN');try{const rows=[];for(const statement of statements)rows.push(await statement.run());sql.exec('COMMIT');return rows;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
async function setup(){const DB=memoryDB(),images=new Map(),env={DB,IMAGES:{async head(key){return images.has(key)?{}:null},async get(key){return images.has(key)?{body:images.get(key),httpMetadata:{contentType:'image/png'}}:null}}},base='https://app.test';const call=(user,path,method='GET',input)=>worker.fetch(new Request(base+'/api/'+path,{method,headers:{Cookie:user?.cookie||'',Origin:base,...(method!=='GET'?{'Content-Type':'application/json'}:{})},...(input?{body:JSON.stringify(input)}:{})}),env);const users=[];for(const username of ['creatoralice','memberbob','outsidereve']){const response=await call(null,'signup','POST',{username,password:'a long secure password'});users.push({...await response.json(),cookie:response.headers.get('Set-Cookie').split(';')[0]});}return {DB,images,call,users};}
test('creator categories support multiple values and keep public recipes on profile-only changes',async()=>{const {call,users:[a,b]}=await setup();const profile={name:'料理人',bio:'紹介',categories:['和食','時短'],enabled:true};assert.equal((await call(a,'creator/profile','PUT',profile)).status,200);const own=await (await call(a,'creator/profile')).json();assert.deepEqual(own.profile.categories.sort(),['和食','時短'].sort());const search=await (await call(b,'creators?category='+encodeURIComponent('時短'))).json();assert.equal(search.creators[0].id,a.user.id);assert.equal((await call(a,'creator/profile','PUT',{...profile,categories:[]})).status,400);assert.equal((await call(a,'creator/profile','PUT',{...profile,categories:['和食','不正']})).status,400);});
test('free invites and paid subscriptions gate recipe snapshots, images and member lists',async()=>{
 const {DB,images,call,users:[a,b,e]}=await setup(),imageId='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';images.set(a.user.id+'/'+imageId,'recipe portrait');
 const recipe={id:10,name:'卵焼き',ingredients:['卵'],time:5,meal:'朝',img:'/api/images/'+imageId,privateNote:'secret',nutritionProfile:{weight:88}},state={recipes:[recipe],foods:[],shopping:[],stores:[],plans:{}};
 assert.equal((await call(a,'data','PUT',{data:state,version:0})).status,200);const profile={name:'料理人',bio:'紹介',categories:['和食','時短'],enabled:true};assert.equal((await call(a,'creator/profile','PUT',profile)).status,200);
 const created=await call(a,'communities','POST',{name:'無料料理クラブ'});assert.equal(created.status,201);const {id:groupId}=await created.json();assert.equal((await (await call(a,'communities')).json()).communities[0].kind,'free');
 const invite=await (await call(a,'sharing/groups/'+groupId+'/invites','POST',{})).json();assert.equal((await call(b,'sharing/join','POST',{code:invite.code})).status,200);assert.equal((await (await call(b,'communities')).json()).communities[0].id,groupId);
 assert.equal((await call(a,'creator/recipe-visibility/10','PUT',{visibility:'limited',groupId})).status,200);const shared=await (await call(b,'sharing/groups/'+groupId)).json();assert.equal(shared.recipes[0].recipe.privateNote,undefined);assert.equal(shared.recipes[0].recipe.nutritionProfile,undefined);assert.equal((await call(b,shared.recipes[0].recipe.img.slice(5))).status,200);assert.equal((await call(e,shared.recipes[0].recipe.img.slice(5))).status,403);
 const response=await call(a,'commerce/products','POST',{kind:'community',title:'月額料理クラブ',summary:'紹介',body:'会員向け',price:500,published:false,ownContent:true});assert.equal(response.status,200);const {id:productId}=await response.json();const paidGroup='paid:'+productId;
 assert.equal((await call(a,'creator/recipe-visibility/10','PUT',{visibility:'limited',groupId:paidGroup})).status,200);assert.equal((await call(b,'commerce/products/'+productId+'/recipes')).status,403);assert.equal((await call(b,'commerce/products/'+productId+'/members')).status,403);assert.equal((await (await call(b,'sharing/groups/'+groupId)).json()).recipes.length,0);
 DB.sql.prepare('INSERT INTO commerce_memberships(subscription_id,user_id,product_id,status,period_end,cancel_at_period_end,updated_at) VALUES(?,?,?,?,?,?,?)').run('sub_fixture',b.user.id,productId,'active',Math.floor(Date.now()/1000)+3600,0,Date.now());
 const paid=await (await call(b,'commerce/products/'+productId+'/recipes')).json();assert.equal(paid.recipes[0].name,'卵焼き');assert.equal(paid.recipes[0].privateNote,undefined);assert.equal((await call(b,paid.recipes[0].img.slice(5))).status,200);assert.equal((await call(e,paid.recipes[0].img.slice(5))).status,403);assert.equal((await (await call(b,'commerce/products/'+productId+'/members')).json()).members.length,2);assert.equal((await call(b,'creator/recipe-visibility/10','PUT',{visibility:'limited',groupId:paidGroup})).status,404);
 assert.equal((await call(a,'creator/recipe-visibility/10','PUT',{visibility:'public'})).status,200);assert.equal((await (await call(b,'commerce/products/'+productId+'/recipes')).json()).recipes.length,0);assert.equal((await call(b,'creators/'+a.user.id+'/recipes/10')).status,200);assert.equal((await call(a,'creator/profile','PUT',{...profile,categories:['洋食','ヘルシー']})).status,200);assert.equal((await call(b,'creators/'+a.user.id+'/recipes/10')).status,200,'profile-only save preserves public recipes');
 assert.equal((await call(a,'creator/recipe-visibility/10','PUT',{visibility:'private'})).status,200);assert.equal((await call(b,'creators/'+a.user.id+'/recipes/10')).status,404);
 DB.sql.prepare('UPDATE commerce_memberships SET period_end=0').run();assert.equal((await call(b,'commerce/products/'+productId+'/members')).status,403);assert.equal((await (await call(b,'communities')).json()).communities.find(c=>c.id===paidGroup).accessible,false);
});
