import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from '../worker.js';
import {verifyStripeSignature} from '../stripe-webhook.js';
const base='https://app.test',pid='12345678-1234-1234-1234-123456789abc';
const database=()=>{const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const prepare=(query,args=[])=>({bind(...p){return prepare(query,p)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}}}});return {prepare,async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}},sql};};
async function signature(raw,stamp=Math.floor(Date.now()/1000)){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode('whsec_test'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(stamp+'.'+raw));return 't='+stamp+',v1='+Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');}
async function setup(kind='content'){
 const DB=database(),env={DB,STRIPE_SECRET_KEY:'sk_test_fake',STRIPE_WEBHOOK_SECRET:'whsec_test'};let calls=0,customerId=0;const state={subscription:{id:'sub_1',metadata:{},status:'active',cancel_at_period_end:false,current_period_end:Math.floor(Date.now()/1000)+86400,latest_invoice:{status:'paid'},items:{data:[{price:{id:'price_1'},current_period_end:Math.floor(Date.now()/1000)+86400}]}},charge:{id:'ch_1',paid:true,amount_refunded:0,disputed:false,payment_intent:'pi_1'},dispute:{id:'dp_1',charge:'ch_1',status:'needs_response'},session:null};
 env.STRIPE_FETCH=async(url,init)=>{calls++;const u=new URL(url),path=u.pathname.replace('/v1',''),f=new URLSearchParams(init.body);assert.equal(init.headers.Authorization,'Bearer sk_test_fake');if(init.method==='POST'){assert.ok(!f.has('email')&&!f.has('name')||path==='/products');if(path==='/customers')return Response.json({id:'cus_'+(++customerId)});if(path==='/products')return Response.json({id:'prod_1'});if(path==='/prices')return Response.json({id:'price_1'});if(path==='/checkout/sessions'){state.session={id:'cs_1',metadata:{user_id:f.get('metadata[user_id]'),product_id:f.get('metadata[product_id]')},client_reference_id:f.get('client_reference_id'),customer:f.get('customer'),mode:f.get('mode'),status:'complete',payment_status:'paid',payment_intent:'pi_1',subscription:'sub_1'};state.subscription.metadata=state.session.metadata;state.subscription.customer=state.session.customer;return Response.json({id:'cs_1',url:'https://checkout.stripe.com/test'});}if(path==='/billing_portal/configurations')return Response.json({id:'bpc_1'});if(path==='/billing_portal/sessions')return Response.json({url:'https://billing.stripe.com/test'});}if(path==='/accounts/acct_1')return Response.json({charges_enabled:true,payouts_enabled:true});if(path==='/checkout/sessions/cs_1')return Response.json(state.session);if(path==='/checkout/sessions/cs_1/line_items')return Response.json({data:[{price:{id:'price_1'},quantity:1}]});if(path==='/payment_intents/pi_1')return Response.json({id:'pi_1',status:'succeeded',latest_charge:state.charge});if(path==='/subscriptions/sub_1')return Response.json(state.subscription);if(path==='/charges/ch_1')return Response.json(state.charge);if(path==='/disputes/dp_1')return Response.json(state.dispute);throw Error('unexpected Stripe request '+path);};
 const call=(path,method='GET',body,cookie='',custom=env)=>worker.fetch(new Request(base+'/api/'+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},...(body!==undefined?{body:JSON.stringify(body)}:{})}),custom);
 async function signup(username){const r=await call('signup','POST',{username,password:'long secure test password'});assert.equal(r.status,200);return {user:(await r.json()).user,cookie:r.headers.get('Set-Cookie').split(';')[0]};}
 const seller=await signup('seller'),buyer=await signup('buyer'),other=await signup('other');await call('creator/profile','PUT',{name:'販売者の表示名',bio:'紹介',category:'和食',enabled:true,recipeIds:[]},seller.cookie);await DB.prepare('INSERT INTO commerce_accounts(creator_id,stripe_account_id,ready,disclosure_url,updated_at) VALUES(?,?,?,?,?)').bind(seller.user.id,'acct_1',1,'https://example.com/terms',Date.now()).run();
 const input={id:pid,kind,title:'オリジナルコンテンツ',summary:'公開の紹介',body:'購入者限定の秘密のレシピ',price:500,published:true,ownContent:true};assert.equal((await call('commerce/products','POST',input,seller.cookie)).status,200);
 async function event(type,obj,id='evt_'+crypto.randomUUID(),account='acct_1'){const raw=JSON.stringify({id,type,account,data:{object:obj}});return worker.fetch(new Request(base+'/api/stripe/webhook',{method:'POST',headers:{'Stripe-Signature':await signature(raw)},body:raw}),env);}
 return {DB,env,state,call,seller,buyer,other,event,input,calls:()=>calls};
}
test('Stripe signature rejects altered payloads, old timestamps and missing signatures',async()=>{const raw='{"ok":true}',sig=await signature(raw);assert.equal(await verifyStripeSignature(raw,sig,'whsec_test'),true);assert.equal(await verifyStripeSignature(raw+' ',sig,'whsec_test'),false);assert.equal(await verifyStripeSignature(raw,await signature(raw,Math.floor(Date.now()/1000)-301),'whsec_test'),false);assert.equal(await verifyStripeSignature(raw,null,'whsec_test'),false);});
test('paid content stays private until a verified paid webhook, then refunds revoke it and duplicate events are harmless',async()=>{
 const t=await setup();assert.equal((await t.call('commerce/products/'+pid)).status,401);let read=await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json();assert.equal(read.product.body,undefined);assert.equal(read.accessible,false);const legacy=await (await t.call('creators/'+t.seller.user.id,'GET',undefined,t.buyer.cookie)).json();assert.deepEqual(legacy.recipes,[]);
 assert.equal((await t.call('commerce/products/'+pid+'/checkout','POST',{},t.buyer.cookie)).status,400);assert.equal((await t.call('commerce/products','POST',t.input,t.other.cookie)).status,400);assert.equal((await t.call('commerce/products/'+pid+'/checkout','POST',{acceptedTerms:true,price:1},t.buyer.cookie)).status,200);assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,false);
 assert.equal((await t.event('checkout.session.completed',{id:'cs_1'},'evt_purchase')).status,200);read=await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json();assert.equal(read.accessible,true);assert.equal(read.product.body,t.input.body);assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.other.cookie)).json()).product.body,undefined);const count=t.calls();assert.equal((await t.event('checkout.session.completed',{id:'cs_1'},'evt_purchase')).status,200);assert.equal(t.calls(),count);
 t.state.charge.amount_refunded=500;assert.equal((await t.event('charge.refunded',{id:'ch_1'})).status,200);assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,false);await t.event('checkout.session.completed',{id:'cs_1'});assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,false);
 assert.deepEqual(t.DB.sql.prepare('PRAGMA table_info(commerce_customers)').all().map(x=>x.name),['user_id','creator_id','stripe_customer_id']);assert.deepEqual(t.DB.sql.prepare('PRAGMA table_info(commerce_events)').all().map(x=>x.name),['event_id','processed_at']);
});
test('monthly access expires, fails closed after payment failure and cancellation, and protects posts/comments',async()=>{
 const t=await setup('community');await t.call('commerce/products/'+pid+'/checkout','POST',{acceptedTerms:true},t.buyer.cookie);assert.equal((await t.event('checkout.session.completed',{id:'cs_1'})).status,200);assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,true);
 const post=await t.call('commerce/products/'+pid+'/posts','POST',{title:'会員レシピ',body:'会員限定の本文'},t.seller.cookie);assert.equal(post.status,200);const postId=(await post.json()).id;assert.equal((await t.call('commerce/products/'+pid+'/posts','GET',undefined,t.other.cookie)).status,403);assert.equal((await t.call('commerce/posts/'+postId+'/comments','POST',{body:'ありがとう'},t.buyer.cookie)).status,200);assert.equal((await t.call('commerce/posts/'+postId+'/comments','GET',undefined,t.other.cookie)).status,403);assert.equal((await t.call('commerce/products/'+pid+'/portal','POST',{},t.other.cookie)).status,404);
 t.state.subscription.cancel_at_period_end=true;await t.event('customer.subscription.updated',{id:'sub_1'});assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,true);assert.equal((await t.call('commerce/products/'+pid+'/portal','POST',{},t.buyer.cookie)).status,200);
 t.state.subscription.items.data[0].current_period_end=1;t.state.subscription.current_period_end=1;await t.event('customer.subscription.updated',{id:'sub_1'});assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,false);
 t.state.subscription.status='past_due';t.state.subscription.latest_invoice.status='open';await t.event('invoice.payment_failed',{subscription:'sub_1'});assert.equal((await t.call('commerce/posts/'+postId+'/comments','POST',{body:'期限後のコメント'},t.buyer.cookie)).status,403);
 t.state.subscription.status='canceled';await t.event('customer.subscription.deleted',{id:'sub_1'});await t.event('customer.subscription.updated',{id:'sub_1'});assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,false);
});
test('unconfigured Stripe allows drafts but prevents publishing and payment; forged webhook cannot grant access',async()=>{
 const t=await setup();const env={DB:t.DB},draft={...t.input,id:'87654321-1234-1234-1234-123456789abc',published:false};assert.equal((await t.call('commerce/products','POST',draft,t.seller.cookie,env)).status,200);assert.equal((await t.call('commerce/products','POST',{...draft,published:true},t.seller.cookie,env)).status,400);assert.equal((await t.call('commerce/products/'+pid+'/checkout','POST',{acceptedTerms:true},t.buyer.cookie,env)).status,503);const raw=JSON.stringify({id:'evt_forged',type:'checkout.session.completed',account:'acct_1',data:{object:{id:'cs_1'}}});const forged=await worker.fetch(new Request(base+'/api/stripe/webhook',{method:'POST',body:raw,headers:{'Stripe-Signature':'t=1,v1=abc'}}),t.env);assert.equal(forged.status,400);assert.equal(t.DB.sql.prepare('SELECT count(*) AS n FROM commerce_events').get().n,0);
});
test('disputes revoke access and only a won, unrefunded dispute restores it; owners can moderate and authors can remove comments',async()=>{
 const t=await setup();await t.call('commerce/products/'+pid+'/checkout','POST',{acceptedTerms:true},t.buyer.cookie);await t.event('checkout.session.completed',{id:'cs_1'});t.state.charge.disputed=true;await t.event('charge.dispute.created',{id:'dp_1'});assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,false);t.state.dispute.status='won';t.state.charge.disputed=false;await t.event('charge.dispute.closed',{id:'dp_1'});assert.equal((await (await t.call('commerce/products/'+pid,'GET',undefined,t.buyer.cookie)).json()).accessible,true);
 const c=await setup('community');await c.call('commerce/products/'+pid+'/checkout','POST',{acceptedTerms:true},c.buyer.cookie);await c.event('checkout.session.completed',{id:'cs_1'});const post=(await (await c.call('commerce/products/'+pid+'/posts','POST',{title:'投稿',body:'内容'},c.seller.cookie)).json()).id;await c.call('commerce/posts/'+post+'/comments','POST',{body:'コメント'},c.buyer.cookie);const comment=c.DB.sql.prepare('SELECT id FROM community_comments').get().id;assert.equal((await c.call('commerce/comments/'+comment,'DELETE',{},c.other.cookie)).status,403);c.state.subscription.status='canceled';await c.event('customer.subscription.deleted',{id:'sub_1'});assert.equal((await c.call('commerce/comments/'+comment,'DELETE',{},c.buyer.cookie)).status,200);assert.equal((await c.call('commerce/posts/'+post,'DELETE',{},c.buyer.cookie)).status,403);assert.equal((await c.call('commerce/posts/'+post,'DELETE',{},c.seller.cookie)).status,200);
});
