import test from 'node:test';
import assert from 'node:assert/strict';
import {publicUrl,publicAddress,fetchRecipePage,pageRecipe,extractRecipe} from '../recipe-import.js';
test('import blocks private destinations including encoded IPs and redirect targets',async()=>{for(const url of ['http://recipes.com','https://localhost','https://127.0.0.1','https://2130706433','https://0x7f000001','https://user:pass@recipes.com','https://recipes.local','https://recipes.com:8080','https://[::1]'])assert.throws(()=>publicUrl(url));assert.equal(publicAddress('10.1.2.3'),false);assert.equal(publicAddress('fc00::1'),false);assert.equal(publicAddress('2001:db8::1'),false);assert.equal(publicAddress('93.184.216.34'),true);let visits=0;const fetcher=async url=>{if(String(url).includes('cloudflare-dns.com'))return Response.json({Status:0,Answer:[{type:1,data:'93.184.216.34'}]});visits++;return new Response(null,{status:302,headers:{Location:'https://127.0.0.1/private'}});};await assert.rejects(()=>fetchRecipePage('https://recipes.com',fetcher));assert.equal(visits,1);await assert.rejects(()=>fetchRecipePage('https://recipes.com',async()=>Response.json({Status:0,Answer:[{type:1,data:'10.0.0.1'}]})));});
test('JSON-LD recipe, relative thumbnail and short attributed description',()=>{const html=`<meta content="料理メモ" property="og:site_name"><script type="application/ld+json">${JSON.stringify({'@graph':[{'@type':['Recipe'],name:'卵 &amp; トマト',description:'短い説明',image:'/thumb.jpg',recipeIngredient:['卵 2個','トマト 100g'],recipeYield:'2人分',totalTime:'PT15M',recipeInstructions:'全文は取り込まない'}]})}</script>`;const r=pageRecipe(html,'https://recipes.com/dish');assert.equal(r.name,'卵 & トマト');assert.equal(r.img,'https://recipes.com/thumb.jpg');assert.equal(r.sourceTitle,'料理メモ');assert.deepEqual(r.recipeIngredients,['卵 2個','トマト 100g']);assert.equal(r.text.includes('全文は'),false);});
test('AI extraction validates unknown quantities and sends a private image as inline data',async()=>{const fixture={name:'卵料理',description:'卵のレシピ',servings:2,time:10,requiredIngredients:[{name:'卵',quantity:2,unit:'個',amountText:'2個'},{name:'塩',quantity:null,unit:'',amountText:'少々'}]};let model,seen;const env={AI:{async run(m,input){model=m;seen=input;return {response:'```json\n'+JSON.stringify(fixture)+'\n```'};}}};const r=await extractRecipe(env,{image:{httpMetadata:{contentType:'image/png'},arrayBuffer:async()=>new Uint8Array([137,80,78]).buffer}});assert.equal(r.requiredIngredients[1].quantity,null);assert.equal(model,'@cf/meta/llama-4-scout-17b-16e-instruct');assert.match(seen.messages[0].content[1].image_url.url,/^data:image\/png;base64,/);fixture.requiredIngredients[0].quantity=-1;await assert.rejects(()=>extractRecipe(env,{image:{httpMetadata:{contentType:'image/png'},arrayBuffer:async()=>new ArrayBuffer(1)}}));});
test('Instagram metadata preserves full caption and user caption extraction returns summarized steps',async()=>{
 const caption='材料：卵2個、トマト1個。作り方：卵を混ぜて、トマトと炒める。';const page=pageRecipe('<meta property="og:description" content="'+caption+'">','https://www.instagram.com/p/ABCdefghijk/');assert.equal(page.isCaption,true);assert.equal(page.text,caption);assert.equal(page.video.kind,'embed');let sent;
 const result=await extractRecipe({AI:{async run(model,input){sent=input;return {response:{name:'卵とトマト炒め',description:'卵とトマトの炒め物',servings:1,time:10,requiredIngredients:[{name:'卵',quantity:2,unit:'個',amountText:'2個'}],steps:['卵を溶く。','トマトと卵を炒め、十分加熱する。']}};}}},{page});assert.equal(result.steps.length,2);assert.match(sent.messages[0].content,/キャプション/);assert.match(sent.messages[1].content,/卵2個/);
});
