import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from '../worker.js';
const base='https://app.test';
function database(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const prepare=(query,args=[])=>({bind(...p){return prepare(query,p)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}}}});return {sql,prepare,async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
async function setup(){const DB=database(),images=new Map(),env={DB,IMAGES:{async head(key){return images.has(key)?{}:null},async get(key){return images.has(key)?{body:images.get(key),httpMetadata:{contentType:'image/png'}}:null}}};const call=(cookie,path,method='GET',input)=>worker.fetch(new Request(base+'/api/'+path,{method,headers:{Cookie:cookie||'',Origin:base,...(method!=='GET'?{'Content-Type':'application/json'}:{})},...(input?{body:JSON.stringify(input)}:{})}),env);const users=[];for(const username of ['alice','bob','eve']){const response=await call('','signup','POST',{username,password:'a long secure password'});users.push({...await response.json(),cookie:response.headers.get('Set-Cookie').split(';')[0]});}const [a,b,c]=users,created=await call(a.cookie,'sharing/groups','POST',{name:'家族'}),group=(await created.json()).group,path='sharing/groups/'+group.id;const join=async()=>{const invite=await (await call(a.cookie,path+'/invites','POST',{})).json();return {invite,response:await call(b.cookie,'sharing/join','POST',{code:invite.code})};};return {DB,images,call,a,b,c,group,path,join};}
const recipe={id:10,name:'卵焼き',ingredients:['卵'],requiredIngredients:[{name:'卵',quantity:2,unit:'個',amountText:'2個'}],steps:['卵を混ぜる'],time:5,meal:'朝',img:'https://images.unsplash.com/food',nutritionProfile:{weight:99},privateNote:'共有禁止'};
test('single-use hashed invites, member-only access and private snapshot allowlist',async()=>{const {DB,call,a,b,c,path,group,join}=await setup();assert.equal((await call(c.cookie,path)).status,403);assert.equal((await call('',path)).status,401);const {invite,response}=await join();assert.equal(response.status,200);assert.equal((await call(c.cookie,'sharing/join','POST',{code:invite.code})).status,404);assert.notEqual(DB.sql.prepare('SELECT token_hash FROM sharing_invites').get().token_hash,invite.code);assert.equal((await call(b.cookie,path+'/invites','POST',{})).status,403);assert.equal((await call(a.cookie,path+'/recipes/10','PUT',{recipe,version:0})).status,200);const data=await (await call(b.cookie,path)).json();assert.equal(data.recipes[0].recipe.name,'卵焼き');assert.equal(data.recipes[0].recipe.privateNote,undefined);assert.equal(data.recipes[0].recipe.nutritionProfile,undefined);assert.equal((await call(b.cookie,'data')).status,200);assert.equal((await (await call(b.cookie,'data')).json()).data,null);assert.equal((await (await call(b.cookie,'sharing')).json()).groups[0].member_count,2);assert.equal(group.owner_id,a.user.id);});
test('shared writes use author identity, stale versions fail and recipes/plans do not expose personal logs',async()=>{const {call,a,b,c,path,join}=await setup();await join();assert.equal((await call(a.cookie,path+'/recipes/10','PUT',{recipe,version:0})).status,200);assert.equal((await call(a.cookie,path+'/recipes/10','PUT',{recipe:{...recipe,name:'上書き'},version:0})).status,409);assert.equal((await call(c.cookie,path+'/recipes/10','PUT',{recipe,version:0})).status,403);await call(b.cookie,path+'/recipes/10','DELETE',{});assert.equal((await (await call(b.cookie,path)).json()).recipes.length,1);const meals={朝:[recipe],昼:[],晩:[]};assert.equal((await call(a.cookie,path+'/plans/2026-10-08','PUT',{meals,mealLog:{secret:'個別'},version:0})).status,200);const shared=await (await call(b.cookie,path)).json();assert.equal(shared.plans[0].meals.朝.length,1);assert.equal(shared.plans[0].mealLog,undefined);assert.equal((await call(a.cookie,path+'/plans/2026-99-99','PUT',{meals,version:0})).status,400);});
test('images require both current membership and an exact shared reference owned by the publishing account',async()=>{const {images,call,a,b,path,join}=await setup();await join();const id='12345678-1234-1234-1234-123456789abc',other='22345678-1234-1234-1234-123456789abc';images.set(a.user.id+'/'+id,'image');images.set(a.user.id+'/'+other,'private');const r={...recipe,img:'/api/images/'+id};assert.equal((await call(b.cookie,path+'/recipes/10','PUT',{recipe:r,version:0})).status,403);assert.equal((await call(a.cookie,path+'/recipes/10','PUT',{recipe:r,version:0})).status,200);const shared=await (await call(b.cookie,path)).json(),img=shared.recipes[0].recipe.img.slice('/api/'.length);assert.equal((await call(b.cookie,img)).status,200);assert.equal((await call(b.cookie,path+'/images/'+a.user.id+'/'+other)).status,404);await call(a.cookie,path+'/members/'+b.user.id,'DELETE',{});assert.equal((await call(b.cookie,img)).status,403);assert.equal((await call(b.cookie,path+'/recipes/11','PUT',{recipe:{...recipe,id:11},version:0})).status,403);});
test('revoked and expired invites fail; leaving removes the member shared copies and group deletion retains private data',async()=>{const {DB,call,a,b,path,join}=await setup();const invite=await (await call(a.cookie,path+'/invites','POST',{})).json();await call(a.cookie,path+'/invites/'+invite.id,'DELETE',{});assert.equal((await call(b.cookie,'sharing/join','POST',{code:invite.code})).status,404);const exp=await (await call(a.cookie,path+'/invites','POST',{})).json();DB.sql.prepare('UPDATE sharing_invites SET expires_at=0 WHERE id=?').run(exp.id);assert.equal((await call(b.cookie,'sharing/join','POST',{code:exp.code})).status,404);await join();await call(b.cookie,path+'/recipes/10','PUT',{recipe,version:0});assert.equal((await call(b.cookie,path+'/members/'+a.user.id,'DELETE',{})).status,403);await call(b.cookie,path+'/members/'+b.user.id,'DELETE',{});assert.equal((await (await call(a.cookie,path)).json()).recipes.length,0);await call(a.cookie,'data','PUT',{data:{recipes:[recipe],foods:[],plans:{},shopping:[],stores:[]},version:0});assert.equal((await call(a.cookie,path,'DELETE',{})).status,200);assert.equal((await (await call(a.cookie,'data')).json()).data.recipes.length,1);assert.equal(DB.sql.prepare('SELECT COUNT(*) n FROM sharing_groups').get().n,0);});
