import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../worker.js';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0002_ai_usage.sql',import.meta.url),'utf8'));sql.exec(readFileSync(new URL('../migrations/0001_accounts.sql',import.meta.url),'utf8'));return {async batch(statements){for(const statement of statements)sql.exec(statement.query)},prepare(query){return {query,bind(...params){return {async first(){return sql.prepare(query).get(...params)||null},async run(){return sql.prepare(query).run(...params)}}}}}}}
const sample={recipes:[{id:1,name:'卵',ingredients:['卵'],time:10,meal:'朝',img:'https://images.unsplash.com/a'}],foods:[],plans:{},shopping:[],stores:[]};
const base='https://konade.example';
function call(db,path,method='GET',data,cookie,origin=base){const headers={'Origin':origin,'Content-Type':'application/json'};if(cookie)headers.Cookie=cookie;return worker.fetch(new Request(base+'/api/'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),{DB:db})}
test('accounts, private data, conflict protection and logout',async()=>{const db=database();assert.equal((await call(db,'data')).status,401);const a=await call(db,'signup','POST',{username:'alice',password:'correct horse battery'});assert.equal(a.status,200);const cookie=a.headers.get('Set-Cookie').split(';')[0];assert.match(a.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal((await call(db,'signup','POST',{username:'alice',password:'another password'})).status,409);assert.equal((await call(db,'login','POST',{username:'alice',password:'wrong password'})).status,401);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie,'https://evil.example')).status,403);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie)).status,200);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie)).status,409);const saved=await (await call(db,'data','GET',undefined,cookie)).json();assert.equal(saved.version,1);assert.deepEqual(saved.data,sample);const b=await call(db,'signup','POST',{username:'bob',password:'another strong password'});const cookieB=b.headers.get('Set-Cookie').split(';')[0];assert.equal((await (await call(db,'data','GET',undefined,cookieB)).json()).data,null);assert.equal((await call(db,'logout','POST',{},cookie)).status,200);assert.equal((await call(db,'me','GET',undefined,cookie)).status,401);const login=await call(db,'login','POST',{username:'alice',password:'correct horse battery'});assert.equal(login.status,200);const newCookie=login.headers.get('Set-Cookie').split(';')[0];assert.equal((await (await call(db,'data','GET',undefined,newCookie)).json()).version,1)});
test('validation and rate limit',async()=>{const db=database();assert.equal((await call(db,'signup','POST',{username:'x',password:'short'})).status,400);for(let i=0;i<19;i++)await call(db,'login','POST',{username:'invalid',password:'short'});assert.equal((await call(db,'login','POST',{username:'invalid',password:'short'})).status,429)});
test('R2 uploads, image isolation, type validation and deletion',async()=>{const db=database(),objects=new Map();const IMAGES={async put(key,value,options){objects.set(key,{key,body:value,httpMetadata:options.httpMetadata,customMetadata:options.customMetadata,size:value.length,uploaded:new Date()})},async get(key){return objects.get(key)||null},async delete(key){objects.delete(key)},async list({prefix}){return {objects:[...objects.values()].filter(x=>x.key.startsWith(prefix)),truncated:false}}};const signup=await call(db,'signup','POST',{username:'photos',password:'a very long password'});const cookie=signup.headers.get('Set-Cookie').split(';')[0];const request=(path,method='GET',payload,extra={})=>worker.fetch(new Request(base+'/api/'+path,{method,headers:{Origin:base,Cookie:cookie,...extra},body:payload}),{DB:db,IMAGES});assert.equal((await request('images','POST','text',{'Content-Type':'image/svg+xml'})).status,415);assert.equal((await request('images','POST','not an image',{'Content-Type':'image/png'})).status,400);const uploaded=await request('images','POST',new Uint8Array([255,216,255,224]),{'Content-Type':'image/jpeg','X-Image-Name':encodeURIComponent('レシート.jpg'),'X-Image-Kind':'receipt'});assert.equal(uploaded.status,201);const image=await uploaded.json();assert.equal((await request('images/'+image.id)).status,200);const list=await (await request('images')).json();assert.equal(list.images[0].name,'レシート.jpg');const other=await call(db,'signup','POST',{username:'other',password:'another long password'});const otherCookie=other.headers.get('Set-Cookie').split(';')[0];const privateRead=await worker.fetch(new Request(base+'/api/images/'+image.id,{headers:{Cookie:otherCookie}}),{DB:db,IMAGES});assert.equal(privateRead.status,404);assert.equal((await request('images/'+image.id,'DELETE','{}',{'Content-Type':'application/json'})).status,200);assert.equal((await request('images/'+image.id)).status,404)});
test('AI plan requires login, validates results and limits daily usage',async()=>{const db=database();let calls=0;const AI={async run(){calls++;return {response:JSON.stringify({meals:['朝','昼','晩'].map(meal=>({meal,name:'卵ごはん',side:'温かいごはん',time:10,ingredients:[{name:'卵',amount:'1個'}],steps:['卵を中心まで十分加熱する。']}))})}}};const signup=await call(db,'signup','POST',{username:'ai_user',password:'a very strong password'});const cookie=signup.headers.get('Set-Cookie').split(';')[0];const input={foods:[{name:'卵',qty:'6個'}],mood:'和食',avoid:'えび',time:20,servings:1};const run=(payload=input,auth=cookie,ai=AI)=>worker.fetch(new Request(base+'/api/ai/plan',{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:auth},body:JSON.stringify(payload)}),{DB:db,AI:ai});assert.equal((await run(input,'')).status,401);assert.equal((await run({...input,time:0})).status,400);assert.equal((await run(input,cookie,null)).status,503);const first=await run();assert.equal(first.status,200);assert.equal((await first.json()).meals.length,3);for(let i=0;i<9;i++)assert.equal((await run()).status,200);assert.equal((await run()).status,429);assert.equal(calls,10)});

test('missing D1 tables are initialized automatically',async()=>{const sql=new DatabaseSync(':memory:');const DB={prepare(query){return {query,bind(...params){return {async first(){return sql.prepare(query).get(...params)||null},async run(){return sql.prepare(query).run(...params)}}}}},async batch(statements){for(const statement of statements)sql.exec(statement.query)}};const response=await call(DB,'signup','POST',{username:'first_user',password:'a long secure password'});assert.equal(response.status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM users').get().n,1);assert.equal(sql.prepare('SELECT count(*) AS n FROM ai_usage').get().n,0)});
