import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../worker.js';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0001_accounts.sql',import.meta.url),'utf8'));return {prepare(query){return {bind(...params){return {async first(){return sql.prepare(query).get(...params)||null},async run(){return sql.prepare(query).run(...params)}}}}}}}
const sample={recipes:[{id:1,name:'卵',ingredients:['卵'],time:10,meal:'朝',img:'https://images.unsplash.com/a'}],foods:[],plans:{},shopping:[],stores:[]};
const base='https://konade.example';
function call(db,path,method='GET',data,cookie,origin=base){const headers={'Origin':origin,'Content-Type':'application/json'};if(cookie)headers.Cookie=cookie;return worker.fetch(new Request(base+'/api/'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),{DB:db})}
test('accounts, private data, conflict protection and logout',async()=>{const db=database();assert.equal((await call(db,'data')).status,401);const a=await call(db,'signup','POST',{username:'alice',password:'correct horse battery'});assert.equal(a.status,200);const cookie=a.headers.get('Set-Cookie').split(';')[0];assert.match(a.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal((await call(db,'signup','POST',{username:'alice',password:'another password'})).status,409);assert.equal((await call(db,'login','POST',{username:'alice',password:'wrong password'})).status,401);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie,'https://evil.example')).status,403);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie)).status,200);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie)).status,409);const saved=await (await call(db,'data','GET',undefined,cookie)).json();assert.equal(saved.version,1);assert.deepEqual(saved.data,sample);const b=await call(db,'signup','POST',{username:'bob',password:'another strong password'});const cookieB=b.headers.get('Set-Cookie').split(';')[0];assert.equal((await (await call(db,'data','GET',undefined,cookieB)).json()).data,null);assert.equal((await call(db,'logout','POST',{},cookie)).status,200);assert.equal((await call(db,'me','GET',undefined,cookie)).status,401);const login=await call(db,'login','POST',{username:'alice',password:'correct horse battery'});assert.equal(login.status,200);const newCookie=login.headers.get('Set-Cookie').split(';')[0];assert.equal((await (await call(db,'data','GET',undefined,newCookie)).json()).version,1)});
test('validation and rate limit',async()=>{const db=database();assert.equal((await call(db,'signup','POST',{username:'x',password:'short'})).status,400);for(let i=0;i<19;i++)await call(db,'login','POST',{username:'invalid',password:'short'});assert.equal((await call(db,'login','POST',{username:'invalid',password:'short'})).status,429)});
