import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../worker.js';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0002_ai_usage.sql',import.meta.url),'utf8'));sql.exec(readFileSync(new URL('../migrations/0001_accounts.sql',import.meta.url),'utf8'));const prepare=(query,params=[])=>({query,params,bind(...p){return prepare(query,p)},async first(){return sql.prepare(query).get(...params)||null},async all(){return {results:sql.prepare(query).all(...params)}},async run(){const result=sql.prepare(query).run(...params);return {meta:{changes:Number(result.changes)}}}});return {prepare,async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
const sample={recipes:[{id:1,name:'卵',ingredients:['卵'],time:10,meal:'朝',img:'https://images.unsplash.com/a'}],foods:[],plans:{},shopping:[],stores:[]};
const base='https://konade.example';
test('multi-dish plans and multiple completion snapshots persist with legacy compatibility',async()=>{const db=database();const signup=await call(db,'signup','POST',{username:'multi_meal',password:'a long secure password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0];const recipes=[1,2,3,4].map(id=>({...sample.recipes[0],id,name:'料理'+id}));const data={...sample,recipes,plans:{'2026-10-06':{'朝':[1,4],'昼':[2],'晩':[3]}},mealLog:{'2026-10-06':{'朝':[{recipeId:1,name:'料理1',nutrition:null},{recipeId:4,name:'料理4',nutrition:null}]},'2026-10-05':{'朝':{recipeId:1,name:'料理1',nutrition:null}}}};assert.equal((await call(db,'data','PUT',{data,version:0},cookie)).status,200);const saved=(await (await call(db,'data','GET',undefined,cookie)).json()).data;assert.deepEqual(saved.plans['2026-10-06']['朝'],[1,4]);assert.equal(saved.mealLog['2026-10-06']['朝'].length,2);data.plans['2026-10-06']['朝']=[1,99];assert.equal((await call(db,'data','PUT',{data,version:1},cookie)).status,400);});
test('image pages are ordered by upload date across all R2 listing pages',async()=>{const db=database();const signup=await call(db,'signup','POST',{username:'image_order',password:'a long secure password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0];const IMAGES={async list({prefix,cursor}){const objects=Array.from({length:101},(_,i)=>({key:prefix+String(i).padStart(8,'0')+'-1234-1234-1234-123456789abc',uploaded:new Date(1700000000000+i*1000),size:10,customMetadata:{name:'画像'+i,kind:'recipe'}}));return cursor?{objects:objects.slice(50),truncated:false}:{objects:objects.slice(0,50),truncated:true,cursor:'page2'};}};const run=cursor=>worker.fetch(new Request(base+'/api/images'+(cursor?'?cursor='+encodeURIComponent(cursor):''),{headers:{Cookie:cookie}}),{DB:db,IMAGES});const first=await (await run()).json();assert.equal(first.images[0].name,'画像100');assert.equal(first.images.length,100);assert.ok(first.cursor);const second=await (await run(first.cursor)).json();assert.equal(second.images[0].name,'画像0');assert.equal(second.images.length,1);assert.equal(second.cursor,null);});
test('recipe image extraction is private, validates structured data and shares AI quota',async()=>{const db=database();const signup=await call(db,'signup','POST',{username:'import_user',password:'a long secure password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0];const id='12345678-1234-1234-1234-123456789abc';const recipe={name:'卵炒め',description:'卵を使う料理',servings:2,time:10,requiredIngredients:[{name:'卵',quantity:.5,unit:'個',amountText:'1/2個'}]};let key,aiCalls=0;const env={DB:db,IMAGES:{async get(k){key=k;return k.endsWith(id)?{size:3,httpMetadata:{contentType:'image/png'},arrayBuffer:async()=>new Uint8Array([137,80,78]).buffer}:null;}},AI:{async run(){aiCalls++;return {response:recipe};}}};const run=(input,auth=cookie)=>worker.fetch(new Request(base+'/api/recipes/import',{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:auth},body:JSON.stringify(input)}),env);assert.equal((await run({kind:'image',imageId:id},'')).status,401);assert.equal((await run({kind:'url',url:'https://127.0.0.1'})).status,400);assert.equal(aiCalls,0);assert.equal((await run({kind:'image',imageId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'})).status,404);const response=await run({kind:'image',imageId:id});assert.equal(response.status,200);assert.equal(key.endsWith('/'+id),true);assert.equal(key.startsWith('12345678'),false);const imported=(await response.json()).recipe;assert.equal(imported.requiredIngredients[0].quantity,.5);const data={...sample,recipes:[{...imported,id:2,meal:'朝',ingredients:['卵']}],shopping:[{name:'卵',qty:.5,unit:'個',done:false}]};assert.equal((await call(db,'data','PUT',{data,version:0},cookie)).status,200);data.recipes[0].requiredIngredients[0].quantity=-1;assert.equal((await call(db,'data','PUT',{data,version:1},cookie)).status,400);for(let n=0;n<9;n++)assert.equal((await run({kind:'image',imageId:id})).status,200);assert.equal((await run({kind:'image',imageId:id})).status,429);});
function call(db,path,method='GET',data,cookie,origin=base){const headers={'Origin':origin,'Content-Type':'application/json'};if(cookie)headers.Cookie=cookie;return worker.fetch(new Request(base+'/api/'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),{DB:db})}
test('accounts, private data, conflict protection and logout',async()=>{const db=database();assert.equal((await call(db,'data')).status,401);const a=await call(db,'signup','POST',{username:'alice',password:'correct horse battery'});assert.equal(a.status,200);const cookie=a.headers.get('Set-Cookie').split(';')[0];assert.match(a.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal((await call(db,'signup','POST',{username:'alice',password:'another password'})).status,409);assert.equal((await call(db,'login','POST',{username:'alice',password:'wrong password'})).status,401);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie,'https://evil.example')).status,403);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie)).status,200);assert.equal((await call(db,'data','PUT',{data:sample,version:0},cookie)).status,409);const saved=await (await call(db,'data','GET',undefined,cookie)).json();assert.equal(saved.version,1);assert.deepEqual(saved.data,sample);const b=await call(db,'signup','POST',{username:'bob',password:'another strong password'});const cookieB=b.headers.get('Set-Cookie').split(';')[0];assert.equal((await (await call(db,'data','GET',undefined,cookieB)).json()).data,null);assert.equal((await call(db,'logout','POST',{},cookie)).status,200);assert.equal((await call(db,'me','GET',undefined,cookie)).status,401);const login=await call(db,'login','POST',{username:'alice',password:'correct horse battery'});assert.equal(login.status,200);const newCookie=login.headers.get('Set-Cookie').split(';')[0];assert.equal((await (await call(db,'data','GET',undefined,newCookie)).json()).version,1)});
test('validation and rate limit',async()=>{const db=database();assert.equal((await call(db,'signup','POST',{username:'x',password:'short'})).status,400);for(let i=0;i<19;i++)await call(db,'login','POST',{username:'invalid',password:'short'});assert.equal((await call(db,'login','POST',{username:'invalid',password:'short'})).status,429)});
test('R2 uploads, image isolation, type validation and deletion',async()=>{const db=database(),objects=new Map();const IMAGES={async put(key,value,options){objects.set(key,{key,body:value,httpMetadata:options.httpMetadata,customMetadata:options.customMetadata,size:value.length,uploaded:new Date()})},async get(key){return objects.get(key)||null},async delete(key){objects.delete(key)},async list({prefix}){return {objects:[...objects.values()].filter(x=>x.key.startsWith(prefix)),truncated:false}}};const signup=await call(db,'signup','POST',{username:'photos',password:'a very long password'});const cookie=signup.headers.get('Set-Cookie').split(';')[0];const request=(path,method='GET',payload,extra={})=>worker.fetch(new Request(base+'/api/'+path,{method,headers:{Origin:base,Cookie:cookie,...extra},body:payload}),{DB:db,IMAGES});assert.equal((await request('images','POST','text',{'Content-Type':'image/svg+xml'})).status,415);assert.equal((await request('images','POST','not an image',{'Content-Type':'image/png'})).status,400);const uploaded=await request('images','POST',new Uint8Array([255,216,255,224]),{'Content-Type':'image/jpeg','X-Image-Name':encodeURIComponent('レシート.jpg'),'X-Image-Kind':'receipt'});assert.equal(uploaded.status,201);const image=await uploaded.json();assert.equal((await request('images/'+image.id)).status,200);const list=await (await request('images')).json();assert.equal(list.images[0].name,'レシート.jpg');const other=await call(db,'signup','POST',{username:'other',password:'another long password'});const otherCookie=other.headers.get('Set-Cookie').split(';')[0];const privateRead=await worker.fetch(new Request(base+'/api/images/'+image.id,{headers:{Cookie:otherCookie}}),{DB:db,IMAGES});assert.equal(privateRead.status,404);assert.equal((await request('images/'+image.id,'DELETE','{}',{'Content-Type':'application/json'})).status,200);assert.equal((await request('images/'+image.id)).status,404)});
test('AI plan requires login, validates results and limits daily usage',async()=>{const db=database();let calls=0;const AI={async run(){calls++;return {response:JSON.stringify({meals:['朝','昼','晩'].map(meal=>({meal,name:'卵ごはん',side:'温かいごはん',time:10,nutrition:{kcal:500,protein:25,fat:15,carbs:66,fiber:8,calcium:260,potassium:1000,salt:1.5},ingredients:[{name:'卵',amount:'1個'}],steps:['卵を中心まで十分加熱する。']}))})}}};const signup=await call(db,'signup','POST',{username:'ai_user',password:'a very strong password'});const cookie=signup.headers.get('Set-Cookie').split(';')[0];const input={foods:[{name:'卵',qty:'6個'}],mood:'和食',avoid:'えび',time:20,servings:1};const run=(payload=input,auth=cookie,ai=AI)=>worker.fetch(new Request(base+'/api/ai/plan',{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:auth},body:JSON.stringify(payload)}),{DB:db,AI:ai});assert.equal((await run(input,'')).status,401);assert.equal((await run({...input,time:0})).status,400);assert.equal((await run(input,cookie,null)).status,503);const first=await run();assert.equal(first.status,200);assert.equal((await first.json()).meals.length,3);for(let i=0;i<9;i++)assert.equal((await run()).status,200);assert.equal((await run()).status,429);assert.equal(calls,10)});

test('missing D1 tables are initialized automatically',async()=>{const sql=new DatabaseSync(':memory:');const DB={prepare(query){return {query,bind(...params){return {async first(){return sql.prepare(query).get(...params)||null},async all(){return {results:sql.prepare(query).all(...params)}},async run(){return sql.prepare(query).run(...params)}}}}},async batch(statements){for(const statement of statements)sql.exec(statement.query)}};const response=await call(DB,'signup','POST',{username:'first_user',password:'a long secure password'});assert.equal(response.status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM users').get().n,1);assert.equal(sql.prepare('SELECT count(*) AS n FROM ai_usage').get().n,0)});
test('AI nutrition targets are calculated on server and enforced',async()=>{const {calculateTargets}=await import('../public/src/nutrition.js');const db=database(),profile={sex:'male',age:30,height:170,weight:60,activity:'low'},target=calculateTargets(profile);const signup=await call(db,'signup','POST',{username:'nutri_user',password:'another long secure password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0];let under=false,seenTarget;const AI={async run(model,input){seenTarget=JSON.parse(input.messages[1].content).nutritionTarget;const n={kcal:target.kcal/3,protein:target.protein/3,fat:target.fat/3,carbs:target.carbs/3,fiber:target.fiber/3,calcium:target.calcium/3,potassium:target.potassium/3,salt:1.5};if(under)n.calcium=0;return {response:{meals:['朝','昼','晩'].map(meal=>({meal,name:'栄養ごはん',side:'バランス食',time:20,nutrition:n,ingredients:[{name:'卵',amount:'1個'}],steps:['十分に加熱する']}))}}}};const request=()=>worker.fetch(new Request(base+'/api/ai/plan',{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({foods:[],mood:'和食',avoid:'',time:30,servings:2,nutritionProfile:profile})}),{DB:db,AI});let response=await request();assert.equal(response.status,200);assert.equal(seenTarget.kcal,2120);under=true;assert.equal((await request()).status,502);const data={...sample,nutritionProfile:profile,mealLog:{'2026-10-05':{'朝':{recipeId:1,name:'卵',nutrition:null,completedAt:new Date().toISOString()}}}};assert.equal((await call(db,'data','PUT',{data,version:0},cookie)).status,200);const saved=await (await call(db,'data','GET',undefined,cookie)).json();assert.deepEqual(saved.data.nutritionProfile,profile);assert.equal(saved.data.mealLog['2026-10-05']['朝'].name,'卵')});
test('food photo analysis is private, draft-only and uses shared AI allowance',async()=>{
  const db=database(),signup=await call(db,'signup','POST',{username:'food_import_user',password:'long secure password food'}),cookie=signup.headers.get('Set-Cookie').split(';')[0],user=(await signup.json()).user;
  const id='12345678-1234-1234-1234-123456789abc';let calls=0;const foods=[{name:'トマト',quantity:2,unit:'個',category:'野菜',expiryDate:'',expiryType:'best-before'}];
  const env={DB:db,IMAGES:{async get(k){return k===user.id+'/'+id?{size:3,httpMetadata:{contentType:'image/png'},arrayBuffer:async()=>new Uint8Array([137,80,78]).buffer}:null;}},AI:{async run(){calls++;return {response:{foods}};}}};
  const run=(imageId=id,auth=cookie)=>worker.fetch(new Request(base+'/api/foods/import',{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:auth},body:JSON.stringify({imageId})}),env);
  assert.equal((await run(id,'')).status,401);assert.equal((await run('invalid')).status,400);assert.equal((await run('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')).status,404);assert.equal(calls,0);
  const first=await run();assert.equal(first.status,200);assert.equal((await first.json()).foods[0].quantity,2);
  assert.equal((await (await call(db,'data','GET',undefined,cookie)).json()).data,null);
  for(let i=0;i<9;i++)assert.equal((await run()).status,200);assert.equal((await run()).status,429);assert.equal(calls,10);
});
test('account changes require current password, preserve data and revoke old sessions',async()=>{
  const db=database(),oldPassword='original account password',newPassword='new account password value';const signup=await call(db,'signup','POST',{username:'account_user',password:oldPassword}),cookie=signup.headers.get('Set-Cookie').split(';')[0],id=(await signup.json()).user.id;
  await call(db,'data','PUT',{data:sample,version:0},cookie);await call(db,'signup','POST',{username:'occupied_user',password:oldPassword});
  assert.equal((await call(db,'account','PUT',{username:'other_user',currentPassword:oldPassword})).status,401);
  assert.equal((await call(db,'account','PUT',{username:'other_user',currentPassword:'wrong password'},cookie)).status,403);
  assert.equal((await call(db,'account','PUT',{username:'occupied_user',currentPassword:oldPassword},cookie)).status,409);
  const renamed=await call(db,'account','PUT',{username:'RENAMED_USER',currentPassword:oldPassword},cookie);assert.equal(renamed.status,200);assert.equal((await renamed.json()).user.username,'renamed_user');
  assert.equal((await call(db,'login','POST',{username:'account_user',password:oldPassword})).status,401);
  const second=await call(db,'login','POST',{username:'renamed_user',password:oldPassword}),otherCookie=second.headers.get('Set-Cookie').split(';')[0];
  assert.equal((await call(db,'account','PUT',{newPassword:'short',currentPassword:oldPassword},cookie)).status,400);
  const changed=await call(db,'account','PUT',{newPassword,currentPassword:oldPassword},cookie);assert.equal(changed.status,200);assert.equal((await changed.json()).user.id,id);const freshCookie=changed.headers.get('Set-Cookie').split(';')[0];
  assert.equal((await call(db,'me','GET',undefined,cookie)).status,401);assert.equal((await call(db,'me','GET',undefined,otherCookie)).status,401);assert.equal((await call(db,'me','GET',undefined,freshCookie)).status,200);
  assert.deepEqual((await (await call(db,'data','GET',undefined,freshCookie)).json()).data,sample);
  assert.equal((await call(db,'login','POST',{username:'renamed_user',password:oldPassword})).status,401);assert.equal((await call(db,'login','POST',{username:'renamed_user',password:newPassword})).status,200);
});
test('individual meal nutrition is authenticated and validated before returning estimates',async()=>{
 const db=database(),signup=await call(db,'signup','POST',{username:'nutrition_import',password:'long nutrition password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0];let seen,invalid=false;
 const nutrition={kcal:500,protein:25,fat:15,carbs:66,fiber:8,calcium:260,potassium:1000,salt:1.5};const env={DB:db,AI:{async run(model,input){seen=JSON.parse(input.messages[1].content);return {response:{nutrition:invalid?{...nutrition,protein:-5}:nutrition,note:'分量不明の材料は1人前の標準量で推定'}};}}};
 const input={name:'トマトと卵',ingredients:[{name:'卵',quantity:null,unit:'',amountText:''}],servings:1};const run=(data=input,auth=cookie)=>worker.fetch(new Request(base+'/api/ai/nutrition',{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:auth},body:JSON.stringify(data)}),env);
 assert.equal((await run(input,'')).status,401);assert.equal((await run({...input,servings:0})).status,400);const response=await run();assert.equal(response.status,200);assert.deepEqual((await response.json()).nutrition,nutrition);assert.equal(seen.servings,1);assert.equal(seen.ingredients[0].quantity,null);invalid=true;assert.equal((await run()).status,502);
});
test('caption import stores structured ingredients and steps and direct videos need no AI',async()=>{
 const db=database(),signup=await call(db,'signup','POST',{username:'caption_user',password:'long caption password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0];let calls=0;const env={DB:db,AI:{async run(){calls++;return {response:{name:'卵炒め',description:'卵の炒め物',servings:1,time:10,requiredIngredients:[{name:'卵',quantity:2,unit:'個',amountText:'2個'}],steps:['卵を溶いて炒める。']}};}}};
 const run=(path,input,auth=cookie)=>worker.fetch(new Request(base+'/api/'+path,{method:'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:auth},body:JSON.stringify(input)}),env);
 const r=await run('recipes/import',{kind:'caption',caption:'卵2個を溶いて、炒める。',url:'https://www.instagram.com/p/ABCdefghijk/'});assert.equal(r.status,200);assert.equal((await r.json()).recipe.steps[0],'卵を溶いて炒める。');assert.equal((await run('recipes/import',{kind:'caption',caption:'少し'})).status,400);const video=await run('recipes/video',{url:'https://youtu.be/abcdefghijk'});assert.equal(video.status,200);assert.equal((await video.json()).video.kind,'embed');assert.equal(calls,1);assert.equal((await run('recipes/video',{url:'https://youtu.be/abcdefghijk'},'')).status,401);
});
test('creator opt-in, search, follow and published snapshots keep private user data separate',async()=>{
 const db=database(),signup=async username=>{const r=await call(db,'signup','POST',{username,password:'creator long password'});return {cookie:r.headers.get('Set-Cookie').split(';')[0],id:(await r.json()).user.id};},owner=await signup('creator_owner'),reader=await signup('creator_reader');
 const privateRecipe={...sample.recipes[0],id:2,name:'非公開のレシピ',privateNote:'secret'},publicRecipe={...sample.recipes[0],name:'公開卵料理',privateNote:'secret',steps:['卵を加熱する'],img:'/api/images/12345678-1234-1234-1234-123456789abc'};
 assert.equal((await call(db,'data','PUT',{data:{...sample,recipes:[publicRecipe,privateRecipe]},version:0},owner.cookie)).status,200);
 assert.equal((await call(db,'creator/profile','GET',undefined,owner.cookie)).status,200);
 const input={name:'たまご先生',bio:'毎日の卵料理',category:'和食',enabled:true,recipeIds:[1]};assert.equal((await call(db,'creator/profile','PUT',input,owner.cookie)).status,200);
 const list=await (await call(db,'creators?search='+encodeURIComponent('たまご')+'&category='+encodeURIComponent('和食'),'GET',undefined,reader.cookie)).json();assert.equal(list.creators.length,1);assert.equal(list.creators[0].following,false);assert.equal(list.creators[0].recipeCount,1);
 assert.equal((await (await call(db,'creators?search=%25','GET',undefined,reader.cookie)).json()).creators.length,0);
 const detail=await (await call(db,'creators/'+owner.id,'GET',undefined,reader.cookie)).json();assert.equal(detail.recipes.length,1);assert.equal(detail.recipes[0].privateNote,undefined);assert.match(detail.recipes[0].img,new RegExp('^/api/creators/'+owner.id+'/images/'));assert.equal((await call(db,'creators/'+owner.id+'/recipes/2','GET',undefined,reader.cookie)).status,404);
 const follow=await call(db,'creators/'+owner.id+'/follow','POST',{},reader.cookie);assert.equal((await follow.json()).creator.followers,1);await call(db,'creators/'+owner.id+'/follow','POST',{},reader.cookie);assert.equal((await (await call(db,'creators?following=1','GET',undefined,reader.cookie)).json()).creators.length,1);
 assert.equal((await call(db,'creators/'+owner.id+'/follow','POST',{},owner.cookie)).status,400);assert.equal((await call(db,'creators/'+owner.id+'/follow','POST',{})).status,401);
 assert.equal((await call(db,'creator/profile','PUT',{...input,recipeIds:[999]},reader.cookie)).status,400);assert.equal((await call(db,'creator/profile','PUT',{...input,recipeIds:[1,1]},owner.cookie)).status,400);
 await call(db,'creators/'+owner.id+'/follow','DELETE',{},reader.cookie);assert.equal((await (await call(db,'creators?following=1','GET',undefined,reader.cookie)).json()).creators.length,0);
 await call(db,'creator/profile','PUT',{...input,enabled:false},owner.cookie);assert.equal((await call(db,'creators/'+owner.id,'GET',undefined,reader.cookie)).status,404);assert.equal((await (await call(db,'creators','GET',undefined,reader.cookie)).json()).creators.length,0);assert.equal((await (await call(db,'creator/profile','GET',undefined,owner.cookie)).json()).recipeIds.length,1);
});
test('creator image endpoint exposes only selected recipe images and hides disabled profiles',async()=>{
 const db=database(),signup=await call(db,'signup','POST',{username:'creator_image',password:'long image password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0],id=(await signup.json()).user.id,imageId='12345678-1234-1234-1234-123456789abc',otherId='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
 await call(db,'data','PUT',{data:{...sample,recipes:[{...sample.recipes[0],img:'/api/images/'+imageId}]},version:0},cookie);const profile={name:'画像の料理人',bio:'写真付きレシピ',category:'洋食',enabled:true,recipeIds:[1]};await call(db,'creator/profile','PUT',profile,cookie);
 let key;const env={DB:db,IMAGES:{async get(k){key=k;return {body:'image bytes',httpMetadata:{contentType:'image/png'}};}}};const run=image=>worker.fetch(new Request(base+'/api/creators/'+id+'/images/'+image,{headers:{Cookie:cookie}}),env);
 assert.equal((await run(imageId)).status,200);assert.equal(key,id+'/'+imageId);assert.equal((await run(otherId)).status,404);await call(db,'creator/profile','PUT',{...profile,enabled:false},cookie);assert.equal((await run(imageId)).status,404);
});
test('archive status persists and seeded samples cannot reappear through data saves',async()=>{
 const db=database(),signup=await call(db,'signup','POST',{username:'archive_user',password:'long archive password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0];const demo={id:1,name:'アボカドと卵のトースト',ingredients:['食パン','アボカド','卵'],img:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop',time:10,meal:'朝'},own={...sample.recipes[0],id:90,archived:true,archivedAt:123};
 const input={...sample,recipes:[demo,own],plans:{'2026-10-06':[1,90,90]}};assert.equal((await call(db,'data','PUT',{data:input,version:0},cookie)).status,200);const saved=(await (await call(db,'data','GET',undefined,cookie)).json()).data;assert.equal(saved.recipes.length,1);assert.equal(saved.recipes[0].archived,true);assert.deepEqual(saved.plans['2026-10-06']['朝'],[]);input.recipes=[{...own,archived:false}];input.plans={};assert.equal((await call(db,'data','PUT',{data:input,version:1},cookie)).status,200);assert.equal((await (await call(db,'data','GET',undefined,cookie)).json()).data.recipes[0].archived,false);
});
test('old DB rows are cleaned with a version update when existing users load their data',async()=>{
 const db=database(),signup=await call(db,'signup','POST',{username:'old_demo_user',password:'long old demo password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0],id=(await signup.json()).user.id;const demo={id:1,name:'アボカドと卵のトースト',ingredients:['食パン','アボカド','卵'],img:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop',time:10,meal:'朝'};await db.prepare('INSERT INTO user_data(user_id,data,version,updated_at) VALUES(?,?,?,?)').bind(id,JSON.stringify({...sample,recipes:[demo,{...sample.recipes[0],id:90}],plans:{'2026-10-06':[1,90,90]}}),5,Date.now()).run();const result=await (await call(db,'data','GET',undefined,cookie)).json();assert.equal(result.version,6);assert.equal(result.data.recipes.length,1);assert.equal(result.data.recipes[0].id,90);const again=await (await call(db,'data','GET',undefined,cookie)).json();assert.equal(again.version,6);
});
test('published demo snapshots are removed while creator profiles stay intact',async()=>{
 const db=database(),signup=await call(db,'signup','POST',{username:'published_demo',password:'long published demo password'}),cookie=signup.headers.get('Set-Cookie').split(';')[0],id=(await signup.json()).user.id;await call(db,'creator/profile','GET',undefined,cookie);
 const demo={id:1,name:'アボカドと卵のトースト',ingredients:['食パン','アボカド','卵'],img:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop',time:10,meal:'朝'};await db.prepare('INSERT INTO creator_profiles(user_id,display_name,bio,category,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,'料理人','','和食',1,1,1).run();await db.prepare('INSERT INTO creator_recipes(creator_id,recipe_id,recipe,published_at) VALUES(?,?,?,?)').bind(id,1,JSON.stringify(demo),1).run();const result=await (await call(db,'creators/'+id,'GET',undefined,cookie)).json();assert.equal(result.creator.name,'料理人');assert.equal(result.recipes.length,0);assert.equal(result.creator.recipeCount,0);
});
