import {commerceSchema} from './commerce-schema.js';
export {commerceSchema};
const uuid=/^[a-f0-9-]{36}$/;
const sid=x=>typeof x==='string'?x:x?.id;
const publicProduct=p=>({id:p.id,creatorId:p.creator_id,kind:p.kind,title:p.title,summary:p.summary,price:p.price,published:!!p.published,createdAt:p.created_at});
function fail(message,status=400){const e=new Error(message);e.status=status;throw e;}
export async function stripeRequest(env,path,{method='GET',account,params,key}={}){
 if(!env.STRIPE_SECRET_KEY)fail('Stripe決済はまだ接続されていません',503);
 const headers={Authorization:'Bearer '+env.STRIPE_SECRET_KEY,'Stripe-Version':'2025-06-30.basil'};
 if(account)headers['Stripe-Account']=account;if(key)headers['Idempotency-Key']=key;
 const init={method,headers,signal:AbortSignal.timeout(20000)};
 if(params){headers['Content-Type']='application/x-www-form-urlencoded';init.body=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]));}
 const response=await (env.STRIPE_FETCH||fetch)('https://api.stripe.com/v1'+path,init);const result=await response.json();if(!response.ok)fail('Stripeの処理に失敗しました。設定を確認して再度お試しください',502);return result;
}
async function ownedProfile(db,user){const p=await db.prepare('SELECT * FROM creator_profiles WHERE user_id=?').bind(user.id).first();if(!p)fail('先にクリエイタープロフィールを保存してください');return p;}
export async function hasCommerceAccess(db,userId,p){if(p.creator_id===userId)return true;if(p.kind==='content')return !!await db.prepare("SELECT session_id FROM commerce_orders WHERE user_id=? AND product_id=? AND status='paid' AND disputed=0 LIMIT 1").bind(userId,p.id).first();return !!await db.prepare("SELECT subscription_id FROM commerce_memberships WHERE user_id=? AND product_id=? AND status='active' AND period_end>? LIMIT 1").bind(userId,p.id,Math.floor(Date.now()/1000)).first();}
async function customer(env,db,user,p,account){const row=await db.prepare('SELECT stripe_customer_id FROM commerce_customers WHERE user_id=? AND creator_id=?').bind(user.id,p.creator_id).first();if(row)return row.stripe_customer_id;const c=await stripeRequest(env,'/customers',{method:'POST',account,key:'customer:'+p.creator_id+':'+user.id,params:{'metadata[user_id]':user.id}});await db.prepare('INSERT INTO commerce_customers(user_id,creator_id,stripe_customer_id) VALUES(?,?,?) ON CONFLICT(user_id,creator_id) DO NOTHING').bind(user.id,p.creator_id,c.id).run();return c.id;}
export async function commerceApi(request,env,user,{body,json}){
 try{return await commerceRoute(request,env,user,{body,json});}catch(e){if(e.status)return json({error:e.message},e.status);throw e;}
}
async function commerceRoute(request,env,user,{body,json}){
 const db=env.DB,url=new URL(request.url),path=url.pathname,origin=url.origin,now=Date.now();
 if(path==='/api/commerce/settings'){
  await ownedProfile(db,user);const a=await db.prepare('SELECT * FROM commerce_accounts WHERE creator_id=?').bind(user.id).first();
  if(request.method==='GET'){let ready=false;if(a&&env.STRIPE_SECRET_KEY){const account=await stripeRequest(env,'/accounts/'+a.stripe_account_id);ready=!!(account.charges_enabled&&account.payouts_enabled);await db.prepare('UPDATE commerce_accounts SET ready=?,updated_at=? WHERE creator_id=?').bind(ready?1:0,now,user.id).run();}const products=await db.prepare('SELECT * FROM commerce_products WHERE creator_id=? ORDER BY created_at DESC').bind(user.id).all();return json({connected:!!a,ready,configured:!!env.STRIPE_SECRET_KEY&&!!env.STRIPE_WEBHOOK_SECRET,mode:env.STRIPE_SECRET_KEY?.includes('_test_')?'test':'live',disclosureUrl:a?.disclosure_url||'',products:products.results.map(p=>({...publicProduct(p),body:p.body,priceLocked:!!p.stripe_price_id}))});}
  if(request.method==='PUT'){const input=await body(request,4096);let u;try{u=new URL(input.disclosureUrl);}catch{fail('特定商取引法・販売条件のURLを確認してください');}if(u.protocol!=='https:')fail('販売条件のURLはHTTPSで指定してください');if(!a)fail('先にStripeの販売者登録を開始してください');await db.prepare('UPDATE commerce_accounts SET disclosure_url=?,updated_at=? WHERE creator_id=?').bind(u.href.slice(0,2000),now,user.id).run();return json({ok:true});}
 }
 if(path==='/api/commerce/connect'&&request.method==='POST'){
  await ownedProfile(db,user);if(!env.STRIPE_SECRET_KEY||!env.STRIPE_WEBHOOK_SECRET)fail('Stripeの接続設定がまだ完了していません',503);
  let a=await db.prepare('SELECT * FROM commerce_accounts WHERE creator_id=?').bind(user.id).first();if(!a){const account=await stripeRequest(env,'/accounts',{method:'POST',key:'connect:'+user.id,params:{type:'express',country:'JP','capabilities[card_payments][requested]':true,'capabilities[transfers][requested]':true,'metadata[creator_id]':user.id}});await db.prepare('INSERT INTO commerce_accounts(creator_id,stripe_account_id,updated_at) VALUES(?,?,?) ON CONFLICT(creator_id) DO NOTHING').bind(user.id,account.id,now).run();a=await db.prepare('SELECT * FROM commerce_accounts WHERE creator_id=?').bind(user.id).first();}
  const link=await stripeRequest(env,'/account_links',{method:'POST',params:{account:a.stripe_account_id,type:'account_onboarding',refresh_url:origin+'/#commerce-settings',return_url:origin+'/#commerce-settings'}});return json({url:link.url});
 }
 if(path==='/api/commerce/dashboard'&&request.method==='POST'){const a=await db.prepare('SELECT * FROM commerce_accounts WHERE creator_id=?').bind(user.id).first();if(!a)fail('Stripeに未接続です');const link=await stripeRequest(env,'/accounts/'+a.stripe_account_id+'/login_links',{method:'POST',params:{}});return json({url:link.url});}
 if(path==='/api/commerce/products'&&request.method==='POST'){
  await ownedProfile(db,user);const input=await body(request,100000),id=input.id||crypto.randomUUID();if(!uuid.test(id)||!['content','community'].includes(input.kind)||typeof input.title!=='string'||!input.title.trim()||input.title.length>100||typeof input.summary!=='string'||input.summary.length>600||typeof input.body!=='string'||input.body.length>30000||!Number.isInteger(input.price)||input.price<100||input.price>100000||typeof input.published!=='boolean'||input.ownContent!==true)fail('タイトル・販売価格・自作コンテンツの確認を見直してください');
  const existing=await db.prepare('SELECT * FROM commerce_products WHERE id=?').bind(id).first();if(existing&&existing.creator_id!==user.id)fail('編集できません',403);if(existing?.stripe_price_id&&(existing.price!==input.price||existing.kind!==input.kind))fail('販売開始後の料金・課金方式は変更できません。新しい単品商品を作成してください');if(input.kind==='community'){const other=await db.prepare("SELECT id FROM commerce_products WHERE creator_id=? AND kind='community' AND id<>?").bind(user.id,id).first();if(other)fail('月額コミュニティは1つまでです');}
  let stripeProduct=existing?.stripe_product_id||null,stripePrice=existing?.stripe_price_id||null;
  if(input.published){if(!input.body.trim())fail('販売するコンテンツやコミュニティの案内を入力してください');const profile=await ownedProfile(db,user),a=await db.prepare('SELECT * FROM commerce_accounts WHERE creator_id=?').bind(user.id).first();if(!profile.enabled||!a?.disclosure_url||!env.STRIPE_WEBHOOK_SECRET)fail('公開プロフィール・販売条件・Stripe設定を完了してください');const account=await stripeRequest(env,'/accounts/'+a.stripe_account_id);if(!account.charges_enabled||!account.payouts_enabled)fail('Stripeの本人確認・銀行口座登録を完了してください');if(!stripeProduct){const product=await stripeRequest(env,'/products',{method:'POST',account:a.stripe_account_id,key:'product:'+id,params:{name:input.title,'metadata[product_id]':id}});stripeProduct=product.id;}if(!stripePrice){const price=await stripeRequest(env,'/prices',{method:'POST',account:a.stripe_account_id,key:'price:'+id+':'+input.price,params:{product:stripeProduct,currency:'jpy',unit_amount:input.price,...(input.kind==='community'?{'recurring[interval]':'month'}:{})}});stripePrice=price.id;}}
  await db.prepare('INSERT INTO commerce_products(id,creator_id,kind,title,summary,body,price,stripe_product_id,stripe_price_id,published,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,title=excluded.title,summary=excluded.summary,body=excluded.body,price=excluded.price,stripe_product_id=excluded.stripe_product_id,stripe_price_id=excluded.stripe_price_id,published=excluded.published,updated_at=excluded.updated_at').bind(id,user.id,input.kind,input.title.trim(),input.summary.trim(),input.body,input.price,stripeProduct,stripePrice,input.published?1:0,existing?.created_at||now,now).run();return json({id});
 }
 if(path==='/api/commerce/library'&&request.method==='GET'){
  const products=await db.prepare("SELECT DISTINCT p.*,c.display_name AS creator_name FROM commerce_products p JOIN creator_profiles c ON c.user_id=p.creator_id WHERE EXISTS(SELECT 1 FROM commerce_orders o WHERE o.product_id=p.id AND o.user_id=?) OR EXISTS(SELECT 1 FROM commerce_memberships m WHERE m.product_id=p.id AND m.user_id=?) ORDER BY p.created_at DESC").bind(user.id,user.id).all();const list=[];for(const p of products.results)list.push({...publicProduct(p),creatorName:p.creator_name,accessible:await hasCommerceAccess(db,user.id,p),membership:p.kind==='community'?await db.prepare('SELECT status,period_end,cancel_at_period_end FROM commerce_memberships WHERE user_id=? AND product_id=? ORDER BY updated_at DESC LIMIT 1').bind(user.id,p.id).first():null});return json({products:list});
 }
 const listing=path.match(/^\/api\/commerce\/creators\/([a-f0-9-]{36})$/);if(listing&&request.method==='GET'){const rows=await db.prepare('SELECT p.* FROM commerce_products p JOIN creator_profiles c ON c.user_id=p.creator_id WHERE p.creator_id=? AND p.published=1 AND c.enabled=1 ORDER BY p.created_at DESC').bind(listing[1]).all();return json({products:rows.results.map(publicProduct)});}
 const match=path.match(/^\/api\/commerce\/products\/([a-f0-9-]{36})(?:\/(checkout|portal|posts))?$/);if(match){const id=match[1],sub=match[2],p=await db.prepare('SELECT * FROM commerce_products WHERE id=?').bind(id).first();if(!p)fail('コンテンツが見つかりません',404);const access=await hasCommerceAccess(db,user.id,p),owner=user.id===p.creator_id;
  if(!sub&&request.method==='GET'){if(!p.published&&!access)fail('コンテンツが見つかりません',404);const creator=await db.prepare('SELECT display_name AS name FROM creator_profiles WHERE user_id=?').bind(p.creator_id).first(),a=await db.prepare('SELECT disclosure_url FROM commerce_accounts WHERE creator_id=?').bind(p.creator_id).first();return json({product:{...publicProduct(p),...(access?{body:p.body}:{})},creatorName:creator?.name||'クリエイター',accessible:access,owner,disclosureUrl:a?.disclosure_url||'',paymentConfigured:!!env.STRIPE_SECRET_KEY&&!!env.STRIPE_WEBHOOK_SECRET});}
  if(sub==='checkout'&&request.method==='POST'){const consent=await body(request,4096);if(consent.acceptedTerms!==true)fail('販売条件を確認してください');if(owner)fail('自分の商品は購入できません');if(access)fail('このコンテンツは利用できます');if(!env.STRIPE_WEBHOOK_SECRET)fail('決済設定が未完了です',503);const profile=await ownedProfile(db,{id:p.creator_id}),a=await db.prepare('SELECT * FROM commerce_accounts WHERE creator_id=?').bind(p.creator_id).first();if(!p.published||!profile.enabled||!a?.disclosure_url||!p.stripe_price_id)fail('現在購入できません');const account=await stripeRequest(env,'/accounts/'+a.stripe_account_id);if(!account.charges_enabled||!account.payouts_enabled)fail('販売者の決済設定を確認中です',503);if(p.kind==='community'){const existing=await db.prepare("SELECT subscription_id FROM commerce_memberships WHERE user_id=? AND product_id=? AND status NOT IN ('canceled','incomplete_expired') LIMIT 1").bind(user.id,p.id).first();if(existing)fail('既存の契約があります。購入・会員管理から支払い方法や解約を確認してください');}const cust=await customer(env,db,user,p,a.stripe_account_id);
   const meta={'metadata[user_id]':user.id,'metadata[product_id]':p.id};const s=await stripeRequest(env,'/checkout/sessions',{method:'POST',account:a.stripe_account_id,key:'checkout:'+p.id+':'+user.id+':'+Math.floor(now/120000),params:{mode:p.kind==='community'?'subscription':'payment',customer:cust,client_reference_id:user.id,'payment_method_types[0]':'card','line_items[0][price]':p.stripe_price_id,'line_items[0][quantity]':1,success_url:origin+'/#content/'+p.id,cancel_url:origin+'/#content/'+p.id,...meta,...(p.kind==='community'?{'subscription_data[metadata][user_id]':user.id,'subscription_data[metadata][product_id]':p.id}:{'payment_intent_data[metadata][user_id]':user.id,'payment_intent_data[metadata][product_id]':p.id})}});
   await db.prepare('INSERT INTO commerce_orders(session_id,user_id,product_id,status,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(session_id) DO NOTHING').bind(s.id,user.id,p.id,'pending',now).run();return json({url:s.url});
  }
  if(sub==='portal'&&request.method==='POST'){if(p.kind!=='community')fail('月額コミュニティで利用できます');const c=await db.prepare('SELECT stripe_customer_id FROM commerce_customers WHERE user_id=? AND creator_id=?').bind(user.id,p.creator_id).first(),a=await db.prepare('SELECT * FROM commerce_accounts WHERE creator_id=?').bind(p.creator_id).first();if(!c||!a)fail('管理できる契約がありません',404);let config=a.portal_config_id;if(!config){const r=await stripeRequest(env,'/billing_portal/configurations',{method:'POST',account:a.stripe_account_id,key:'portal:'+p.creator_id,params:{'features[subscription_cancel][enabled]':true,'features[subscription_cancel][mode]':'at_period_end','features[payment_method_update][enabled]':true,'features[invoice_history][enabled]':true,'features[customer_update][enabled]':false,'business_profile[privacy_policy_url]':origin+'/#payment-privacy'}});config=r.id;await db.prepare('UPDATE commerce_accounts SET portal_config_id=? WHERE creator_id=?').bind(config,p.creator_id).run();}const session=await stripeRequest(env,'/billing_portal/sessions',{method:'POST',account:a.stripe_account_id,params:{customer:c.stripe_customer_id,configuration:config,return_url:origin+'/#purchases'}});return json({url:session.url});}
  if(sub==='posts'){if(p.kind!=='community')fail('コミュニティではありません');if(!access)fail('会員限定です',403);if(request.method==='GET'){const posts=await db.prepare('SELECT * FROM community_posts WHERE product_id=? ORDER BY created_at DESC LIMIT 100').bind(p.id).all();return json({posts:posts.results});}if(request.method==='POST'){if(!owner)fail('投稿できるのはクリエイターのみです',403);const i=await body(request,60000);if(typeof i.title!=='string'||!i.title.trim()||i.title.length>100||typeof i.body!=='string'||!i.body.trim()||i.body.length>30000)fail('タイトルと投稿内容を確認してください');const postId=crypto.randomUUID();await db.prepare('INSERT INTO community_posts(id,product_id,title,body,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(postId,p.id,i.title.trim(),i.body,now,now).run();return json({id:postId});}}
 }
 const comments=path.match(/^\/api\/commerce\/posts\/([a-f0-9-]{36})\/comments$/);if(comments){const post=await db.prepare('SELECT * FROM community_posts WHERE id=?').bind(comments[1]).first();if(!post)fail('投稿がありません',404);const p=await db.prepare('SELECT * FROM commerce_products WHERE id=?').bind(post.product_id).first();if(!await hasCommerceAccess(db,user.id,p))fail('会員限定です',403);if(request.method==='GET'){const rows=await db.prepare('SELECT c.id,c.body,c.created_at,c.user_id,u.username AS name FROM community_comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=? ORDER BY c.created_at DESC LIMIT 100').bind(post.id).all();return json({comments:rows.results.map(({user_id,...c})=>({...c,canDelete:user_id===user.id||p.creator_id===user.id}))});}if(request.method==='POST'){const input=await body(request,6000);if(typeof input.body!=='string'||!input.body.trim()||input.body.length>1000)fail('コメントは1〜1000文字で入力してください');const recent=await db.prepare('SELECT created_at FROM community_comments WHERE user_id=? ORDER BY created_at DESC LIMIT 1').bind(user.id).first();if(recent&&now-recent.created_at<10000)fail('少し時間をあけて投稿してください',429);await db.prepare('INSERT INTO community_comments(id,post_id,user_id,body,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),post.id,user.id,input.body.trim(),now).run();return json({ok:true});}}
 const deletion=path.match(/^\/api\/commerce\/(comments|posts)\/([a-f0-9-]{36})$/);if(deletion&&request.method==='DELETE'){if(deletion[1]==='comments'){const row=await db.prepare('SELECT c.user_id,p.creator_id FROM community_comments c JOIN community_posts s ON s.id=c.post_id JOIN commerce_products p ON p.id=s.product_id WHERE c.id=?').bind(deletion[2]).first();if(!row)fail('コメントがありません',404);if(row.user_id!==user.id&&row.creator_id!==user.id)fail('削除できません',403);await db.prepare('DELETE FROM community_comments WHERE id=?').bind(deletion[2]).run();}else{const row=await db.prepare('SELECT p.creator_id FROM community_posts s JOIN commerce_products p ON p.id=s.product_id WHERE s.id=?').bind(deletion[2]).first();if(!row)fail('投稿がありません',404);if(row.creator_id!==user.id)fail('削除できません',403);await db.batch([db.prepare('DELETE FROM community_comments WHERE post_id=?').bind(deletion[2]),db.prepare('DELETE FROM community_posts WHERE id=?').bind(deletion[2])]);}return json({ok:true});}
 fail('ページがありません',404);
}
