export const creatorSchema=["CREATE TABLE IF NOT EXISTS creator_profiles (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, display_name TEXT NOT NULL, bio TEXT NOT NULL DEFAULT '', category TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)","CREATE TABLE IF NOT EXISTS creator_follows (follower_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, creator_id TEXT NOT NULL REFERENCES creator_profiles(user_id) ON DELETE CASCADE, created_at INTEGER NOT NULL, PRIMARY KEY(follower_id,creator_id))","CREATE INDEX IF NOT EXISTS creator_follows_creator ON creator_follows(creator_id)","CREATE TABLE IF NOT EXISTS creator_recipes (creator_id TEXT NOT NULL REFERENCES creator_profiles(user_id) ON DELETE CASCADE, recipe_id INTEGER NOT NULL, recipe TEXT NOT NULL, access_level TEXT NOT NULL DEFAULT 'free' CHECK(access_level='free'), published_at INTEGER NOT NULL, PRIMARY KEY(creator_id,recipe_id))"];
export const creatorCategories=['和食','洋食','中華','ヘルシー','お菓子','時短','作り置き','その他'];
const cardSql=`SELECT p.user_id AS id,p.display_name AS name,p.bio,p.category,p.enabled, (SELECT COUNT(*) FROM creator_follows WHERE creator_id=p.user_id) AS followers,(SELECT COUNT(*) FROM creator_recipes WHERE creator_id=p.user_id) AS recipeCount,EXISTS(SELECT 1 FROM creator_follows WHERE creator_id=p.user_id AND follower_id=?) AS following FROM creator_profiles p`;
const card=p=>({...p,enabled:!!p.enabled,following:!!p.following});
function publishedRecipe(r,id){
 const allowed=['id','name','description','side','time','meal','mood','ingredients','requiredIngredients','ingredientAmounts','steps','servings','nutrition','nutritionSource','nutritionNote','img','url','sourceTitle','video','createdAt'];const result=Object.fromEntries(allowed.filter(k=>r[k]!==undefined).map(k=>[k,r[k]]));
 const image=String(r.img||'').match(/^\/api\/images\/([a-f0-9-]{36})$/);if(image)result.img='/api/creators/'+id+'/images/'+image[1];return result;
}
export async function creatorsApi(request,env,user,{body,json}){
 const url=new URL(request.url),path=url.pathname,db=env.DB,now=Date.now();
 if(path==='/api/creator/profile'){
  if(request.method==='GET'){const profile=await db.prepare(cardSql+' WHERE p.user_id=?').bind(user.id,user.id).first();const recipes=await db.prepare('SELECT recipe_id FROM creator_recipes WHERE creator_id=? ORDER BY published_at DESC').bind(user.id).all();return json({profile:profile?card(profile):null,recipeIds:recipes.results.map(r=>r.recipe_id)});}
  if(request.method==='PUT'){
   const input=await body(request,30000);if(typeof input.name!=='string'||!input.name.trim()||input.name.length>60||typeof input.bio!=='string'||input.bio.length>600||!creatorCategories.includes(input.category)||typeof input.enabled!=='boolean'||!Array.isArray(input.recipeIds)||input.recipeIds.length>100||input.recipeIds.some(id=>!Number.isSafeInteger(id))||new Set(input.recipeIds).size!==input.recipeIds.length)return json({error:'表示名・紹介・カテゴリ・公開レシピを確認してください'},400);
   const row=await db.prepare('SELECT data FROM user_data WHERE user_id=?').bind(user.id).first(),recipes=row?JSON.parse(row.data).recipes:[],selected=input.recipeIds.map(id=>recipes.find(r=>r.id===id));if(selected.some(r=>!r))return json({error:'公開するレシピを先に保存してください'},400);
   const current=await db.prepare('SELECT recipe_id,published_at FROM creator_recipes WHERE creator_id=?').bind(user.id).all(),times=new Map(current.results.map(r=>[r.recipe_id,r.published_at]));
   await db.batch([db.prepare('INSERT INTO creator_profiles(user_id,display_name,bio,category,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET display_name=excluded.display_name,bio=excluded.bio,category=excluded.category,enabled=excluded.enabled,updated_at=excluded.updated_at').bind(user.id,input.name.trim(),input.bio.trim(),input.category,input.enabled?1:0,now,now),db.prepare('DELETE FROM creator_recipes WHERE creator_id=?').bind(user.id),...selected.map((r,i)=>db.prepare('INSERT INTO creator_recipes(creator_id,recipe_id,recipe,published_at) VALUES(?,?,?,?)').bind(user.id,r.id,JSON.stringify(publishedRecipe(r,user.id)),times.get(r.id)||now+i))]);
   return json({id:user.id});
  }return json({error:'許可されていない操作です'},405);
 }
 if(path==='/api/creators'&&request.method==='GET'){
  const search=(url.searchParams.get('search')||'').trim(),category=url.searchParams.get('category')||'',following=url.searchParams.get('following')==='1',offset=Number(url.searchParams.get('offset')||0);if(search.length>100||(category&&!creatorCategories.includes(category))||!Number.isInteger(offset)||offset<0||offset>10000)return json({error:'検索条件を確認してください'},400);
  const escaped=search.replace(/[\\%_]/g,c=>'\\'+c),result=await db.prepare(cardSql+" WHERE p.enabled=1 AND p.user_id<>? AND (?='' OR p.display_name LIKE ? ESCAPE '\\') AND (?='' OR p.category=?) AND (?=0 OR EXISTS(SELECT 1 FROM creator_follows WHERE creator_id=p.user_id AND follower_id=?)) ORDER BY p.created_at DESC,p.user_id LIMIT 51 OFFSET ?").bind(user.id,user.id,search,'%'+escaped+'%',category,category,following?1:0,user.id,offset).all();return json({creators:result.results.slice(0,50).map(card),nextOffset:result.results.length>50?offset+50:null});
 }
 const match=path.match(/^\/api\/creators\/([a-f0-9-]{36})(?:\/(follow|recipes\/\d+|images\/[a-f0-9-]{36}))?$/);if(!match)return json({error:'ページがありません'},404);const id=match[1],sub=match[2];
 const profile=await db.prepare(cardSql+' WHERE p.user_id=? AND p.enabled=1').bind(user.id,id).first();if(!profile)return json({error:'クリエイターが見つかりません'},404);
 if(sub==='follow'){
  if(id===user.id)return json({error:'自分のアカウントはフォローできません'},400);
  if(request.method==='POST')await db.prepare('INSERT INTO creator_follows(follower_id,creator_id,created_at) VALUES(?,?,?) ON CONFLICT(follower_id,creator_id) DO NOTHING').bind(user.id,id,now).run();else if(request.method==='DELETE')await db.prepare('DELETE FROM creator_follows WHERE follower_id=? AND creator_id=?').bind(user.id,id).run();else return json({error:'許可されていない操作です'},405);
  const updated=await db.prepare(cardSql+' WHERE p.user_id=?').bind(user.id,id).first();return json({creator:card(updated)});
 }
 if(request.method!=='GET')return json({error:'許可されていない操作です'},405);
 if(sub?.startsWith('images/')){const imageId=sub.slice(7),allowed=await db.prepare("SELECT recipe_id FROM creator_recipes WHERE creator_id=? AND json_extract(recipe,'$.img')=? LIMIT 1").bind(id,path).first();if(!allowed)return json({error:'画像がありません'},404);const image=await env.IMAGES?.get(id+'/'+imageId);if(!image)return json({error:'画像がありません'},404);return new Response(image.body,{headers:{'Content-Type':image.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'private, no-store'}});}
 if(sub?.startsWith('recipes/')){const row=await db.prepare('SELECT recipe FROM creator_recipes WHERE creator_id=? AND recipe_id=?').bind(id,Number(sub.slice(8))).first();return row?json({creator:card(profile),recipe:JSON.parse(row.recipe)}):json({error:'レシピが見つかりません'},404);}
 const recipes=await db.prepare('SELECT recipe,published_at FROM creator_recipes WHERE creator_id=? ORDER BY published_at DESC,recipe_id DESC LIMIT 100').bind(id).all();return json({creator:card(profile),recipes:recipes.results.map(r=>({...JSON.parse(r.recipe),publishedAt:r.published_at}))});
}
