import {stripeRequest} from './commerce.js';
const sid=x=>typeof x==='string'?x:x?.id;
export async function verifyStripeSignature(raw,header,secret,now=Date.now()){
 if(!secret||!header)return false;const parts=header.split(',').map(x=>x.split('=')),stamp=parts.find(([k])=>k==='t')?.[1],signatures=parts.filter(([k])=>k==='v1').map(([,v])=>v);if(!/^\d+$/.test(stamp||'')||Math.abs(now/1000-Number(stamp))>300)return false;
 const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),digest=await crypto.subtle.sign('HMAC',key,enc.encode(stamp+'.'+raw)),hex=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');return signatures.some(s=>{if(!/^[a-f0-9]{64}$/.test(s||''))return false;let diff=0;for(let i=0;i<64;i++)diff|=hex.charCodeAt(i)^s.charCodeAt(i);return diff===0;});
}
async function syncSubscription(env,account,id){
 const db=env.DB,s=await stripeRequest(env,'/subscriptions/'+encodeURIComponent(id)+'?expand%5B%5D=latest_invoice',{account:account.stripe_account_id}),uid=s.metadata?.user_id,pid=s.metadata?.product_id;
 const p=await db.prepare('SELECT * FROM commerce_products WHERE id=? AND creator_id=?').bind(pid||'',account.creator_id).first();if(!p||p.kind!=='community')return [];
 const cust=await db.prepare('SELECT stripe_customer_id FROM commerce_customers WHERE user_id=? AND creator_id=?').bind(uid||'',p.creator_id).first();if(!cust||cust.stripe_customer_id!==sid(s.customer)||!s.items?.data?.some(item=>sid(item.price)===p.stripe_price_id))return [];
 const matchingItem=s.items.data.find(i=>sid(i.price)===p.stripe_price_id),period=Number(matchingItem.current_period_end||s.current_period_end)||0,active=s.status==='active'&&s.latest_invoice?.status==='paid';
 return [db.prepare('INSERT INTO commerce_memberships(subscription_id,user_id,product_id,status,period_end,cancel_at_period_end,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(subscription_id) DO UPDATE SET status=excluded.status,period_end=excluded.period_end,cancel_at_period_end=excluded.cancel_at_period_end,updated_at=excluded.updated_at').bind(s.id,uid,p.id,active?'active':s.status==='active'?'payment_pending':s.status,period,s.cancel_at_period_end?1:0,Date.now())];
}
export async function stripeWebhook(request,env,json){
 if(!env.STRIPE_WEBHOOK_SECRET||!env.STRIPE_SECRET_KEY)return json({error:'決済設定が未完了です'},503);if(request.method!=='POST')return json({error:'POSTが必要です'},405);
 const reader=request.body?.getReader();if(!reader)return json({error:'不正なイベントです'},400);let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>524288){await reader.cancel();return json({error:'イベントが大きすぎます'},413);}chunks.push(value);}const bytes=new Uint8Array(size);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.length;}const raw=new TextDecoder().decode(bytes);
 if(!await verifyStripeSignature(raw,request.headers.get('Stripe-Signature'),env.STRIPE_WEBHOOK_SECRET))return json({error:'署名を確認できません'},400);
 let e;try{e=JSON.parse(raw);}catch{return json({error:'イベントを確認できません'},400);}if(typeof e.id!=='string'||!e.id.startsWith('evt_')||typeof e.type!=='string'||!e.data?.object)return json({error:'イベントを確認できません'},400);
 const db=env.DB;if(await db.prepare('SELECT event_id FROM commerce_events WHERE event_id=?').bind(e.id).first())return json({received:true});const account=await db.prepare('SELECT * FROM commerce_accounts WHERE stripe_account_id=?').bind(e.account||'').first();if(!account)return json({received:true});const aid=account.stripe_account_id,object=e.data.object,statements=[];
 // Re-read current Stripe objects so delayed events cannot re-enable canceled subscriptions.
 if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(e.type)){
  const s=await stripeRequest(env,'/checkout/sessions/'+encodeURIComponent(object.id),{account:aid});const p=await db.prepare('SELECT * FROM commerce_products WHERE id=? AND creator_id=?').bind(s.metadata?.product_id||'',account.creator_id).first();const cust=await db.prepare('SELECT stripe_customer_id FROM commerce_customers WHERE user_id=? AND creator_id=?').bind(s.metadata?.user_id||'',account.creator_id).first();if(p&&cust&&cust.stripe_customer_id===sid(s.customer)&&s.client_reference_id===s.metadata.user_id&&s.status==='complete'&&s.payment_status==='paid'){
   if(p.kind==='community'&&s.mode==='subscription'&&sid(s.subscription))statements.push(...await syncSubscription(env,account,sid(s.subscription)));
   if(p.kind==='content'&&s.mode==='payment'&&sid(s.payment_intent)){const pending=await db.prepare('SELECT * FROM commerce_orders WHERE session_id=? AND user_id=? AND product_id=?').bind(s.id,s.metadata.user_id,p.id).first();if(pending){const lines=await stripeRequest(env,'/checkout/sessions/'+encodeURIComponent(s.id)+'/line_items',{account:aid});if(lines.data?.length===1&&sid(lines.data[0].price)===p.stripe_price_id&&lines.data[0].quantity===1){const pi=await stripeRequest(env,'/payment_intents/'+encodeURIComponent(sid(s.payment_intent))+'?expand%5B%5D=latest_charge',{account:aid}),charge=pi.latest_charge;const paid=pi.status==='succeeded'&&charge?.paid&&!charge.amount_refunded&&!charge.disputed;statements.push(db.prepare("UPDATE commerce_orders SET payment_intent_id=?,status=?,updated_at=? WHERE session_id=? AND disputed=0").bind(pi.id,paid?'paid':'revoked',Date.now(),s.id));}}}
  }
 }
 if(e.type.startsWith('customer.subscription.'))statements.push(...await syncSubscription(env,account,object.id));
 if(['invoice.paid','invoice.payment_failed'].includes(e.type)){const subscription=sid(object.subscription)||sid(object.parent?.subscription_details?.subscription);if(subscription)statements.push(...await syncSubscription(env,account,subscription));}
 if(e.type==='charge.refunded'){const charge=await stripeRequest(env,'/charges/'+encodeURIComponent(object.id),{account:aid});if(charge.amount_refunded>0&&sid(charge.payment_intent))statements.push(db.prepare("UPDATE commerce_orders SET status='revoked',updated_at=? WHERE payment_intent_id=? AND product_id IN (SELECT id FROM commerce_products WHERE creator_id=?)").bind(Date.now(),sid(charge.payment_intent),account.creator_id));}
 if(['charge.dispute.created','charge.dispute.closed'].includes(e.type)){const d=await stripeRequest(env,'/disputes/'+encodeURIComponent(object.id),{account:aid}),charge=await stripeRequest(env,'/charges/'+encodeURIComponent(sid(d.charge)),{account:aid});const blocked=d.status!=='won',status=!blocked&&charge.paid&&!charge.amount_refunded?'paid':'revoked';statements.push(db.prepare('UPDATE commerce_orders SET status=?,disputed=?,updated_at=? WHERE payment_intent_id=? AND product_id IN (SELECT id FROM commerce_products WHERE creator_id=?)').bind(status,blocked?1:0,Date.now(),sid(charge.payment_intent),account.creator_id));}
 statements.push(db.prepare('INSERT INTO commerce_events(event_id,processed_at) VALUES(?,?) ON CONFLICT(event_id) DO NOTHING').bind(e.id,Date.now()));await db.batch(statements);return json({received:true});
}
